### ISSUE TITLE
Mailchannels: Better Error Message on Failure

### ISSUE THREAD

**Issue by hekuli** [cloudflare/pages-plugins#58]
I've followed the docs trying to get Mailchannels working:
- https://blog.cloudflare.com/sending-email-from-workers-with-mailchannels
- https://developers.cloudflare.com/pages/functions/plugins/mailchannels/

But I always just get the error message:
`Could not send your email. Please try again.`

The source of which I discovered here:

https://github.com/cloudflare/pages-plugins/blob/main/packages/mailchannels/functions/_middleware.ts#L100-L102

A more descriptive error would be more helpful for debugging problems. When googling I've noticed a lot of others get confused too. I think more information would be much appreciated. Or at least return the error so our users code can choose to log it etc.

Is there any way to get more info or debug how configuration is failing?

**Comment by Cherry** [comment]
MailChannels has officially announced an End of Life for their Workers integration:

https://community.cloudflare.com/t/mailchannels-end-of-life-notice-migrate-now/658638

I've opened a PR to remove the plugin since it'll become inoperable in just over a month (https://github.com/cloudflare/pages-plugins/pull/63) and I would encourage you to migrate to alternatives.

**Comment by GregBrimble** [comment]
Thanks for filing this issue. As @Cherry said, this plugin has now been deprecated on account of MailChannels' sunsetting of their free email sending API, so I'm going to close out this issue.
